// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGPTResponse(arg1:string):Promise<string>;

export function GetUserName():Promise<string>;
